# Generated by Django 3.0.7 on 2020-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='target',
            name='radius',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
